# Generated by Django 5.1.2 on 2024-11-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('casadepaz', 'Casa de Paz'), ('discipulado', 'Discipulado'), ('aviva2', 'Aviva2'), ('avivakids', 'Avivakids'), ('jovenes', 'Jovenes')], default='', max_length=20),
        ),
    ]
