# Generated by Django 5.1.2 on 2025-02-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_user_task_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='username',
            new_name='user',
        ),
    ]
