# Generated by Django 5.1.2 on 2025-02-03 01:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
